###################  itlearning配置  ###################
itlearning:
  swagger-open: false #是否开启swagger (true/false)
#  kaptcha-open: false #是否开启登录时验证码 (true/false)
#  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
#  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
#  muti-datasource-open: false #是否开启多数据源(true/false)
#  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
#  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
#  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

server:
    port: @server.port@
    contextPath: @server.contextpath@

spring:
    profiles:
        active: @spring.profiles.active@
    application:
        name:
    jackson:
        serialization.write_dates_as_timestamps: false
        deserialization.FAIL_ON_UNKNOWN_PROPERTIES: off
    messages:
        basename: i18n/messages
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: @datasource.driver@
        url: @datasource.url@
        username: @datasource.username@
        password: @datasource.password@
        test-while-idle: true
        max-wait-millis: 30000
        validation-query: 'SELECT 1'
        time-between-eviction-runs-millis: 20000
        min-evictable-idle-time-millis: 28700
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
    jpa:
        database-platform: @datasource.dialect@
        hibernate:
            ddl-auto: @datasource.jpa.hibernate.ddl-auto@
        show-sql: @datasource.jpa.show-sql@
        filters: log4j,wall,mergeStat
    springfox.documentation.swagger.v2.path: /api-docs




